version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 20
    commit-message:
      prefix: "chore"
    reviewers:
      - "igor-karpukhin"
      - "helderjs" 
      - "josvazg"
      - "roothorp"
      - "s-urbaniak"
    ignore:
      - dependency-name: "go.mongodb.org/atlas-sdk/*"
    groups:
      golang:
        patterns:
          - "golang.org*"
      kubernetes:
        patterns:
          - "*k8s.io*"
      google:
        patterns:
          - "*google.golang.org*"
