name: Snyk Monitor
on:
  pull_request:  # tmp for testing
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk Monitor
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        with:
          command: monitor
