name: Update Compliance Report

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'atlas-cli-plugin tag version (e.g. 1.42.2)'
        required: true
        type: string

jobs:
  update-compliance-report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APIXBOT_APP_ID }}
          private-key: ${{ secrets.APIXBOT_APP_PEM }}
          owner: ${{ github.repository_owner }}
          repositories: atlas-cli-plugin-kubernetes

      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref_name }}
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - name: Extract AUTHOR and VERSION
        id: extract
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            TAG="${{ github.event.inputs.tag }}"
            VERSION="${TAG#atlas-cli-plugin/v}"
            AUTHOR="${{ github.actor }}"
          else
            VERSION="${GITHUB_REF#refs/tags/atlas-cli-plugin/v}"
            AUTHOR="${{ github.event.release.author.login }}"
          fi
          echo "author=$AUTHOR" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Generate Compliance Report
        env: 
          AUTHOR: ${{ steps.extract.outputs.author }}
          VERSION: ${{ steps.extract.outputs.version }}
        run: ./build/package/gen-ssdlc-report.sh
