name: Update PURLs list of dependencies with dependabot

on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  update-purls:
    name: Update PURLs list of dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: mongodb/apix-action/token@v8
        with:
          app-id: ${{ secrets.APIXBOT_APP_ID }}
          private-key: ${{ secrets.APIXBOT_APP_PEM }}

      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - name: Install Go dependencies
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Generate dependency list
        run: make generate-purls

      - name: Commit updated purls.txt if changed
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          echo "Checking for changes to purls.txt..."
          if git diff --quiet --exit-code -- build/package/purls.txt; then
            echo "No changes to purls.txt"
          else 
            echo "Changes detected. Committing..."
            git config --global user.name "${{ steps.generate_token.outputs.user-name }}"
            git config --global user.email "${{ steps.generate_token.outputs.user-email }}"
            git add build/package/purls.txt
            git commit -m "chore: update purls.txt"
            git push origin "$BRANCH_NAME"
          fi
